<?php

namespace App\Http\Controllers;

use Inertia\Inertia;
use Inertia\Response;

/**
 * The offer of source required by section 13 of the AGPL.
 *
 * Anyone interacting with Padiush over a network is entitled to the source of
 * the version they are using. This page is that offer, so it is reachable
 * without signing in and without the public marketing pages being enabled — a
 * deployment that publishes nothing else still publishes this.
 */
class SoftwareNoticeController extends Controller
{
    public function show(): Response
    {
        return Inertia::render('SoftwareNotice', [
            'sourceUrl' => config('padiush.source_url'),
            'appName' => config('app.name'),
            'hasLicences' => file_exists($this->licencesPath()),
        ]);
    }

    /**
     * Attribution for the open-source packages that reach the browser.
     *
     * MIT, ISC and BSD all require their notice to travel with the copies they
     * are in, and a minified bundle strips the comments that would have
     * carried it. FontAwesome's free icons are CC BY 4.0, which requires
     * attribution outright.
     */
    public function licences(): Response
    {
        $path = $this->licencesPath();

        // Generated by `npm run build`. A deployment that has not built its
        // assets has nothing to attribute yet, and an empty page would be a
        // worse answer than saying so.
        abort_unless(file_exists($path), 404);

        return Inertia::render('SoftwareLicences', [
            'licences' => json_decode(file_get_contents($path), true),
        ]);
    }

    private function licencesPath(): string
    {
        return public_path('build/licenses.json');
    }
}
